# render.yaml - CORRECTED FOR YOUR REPO STRUCTURE

# This defines the services and a persistent database for your application.
# Render will create all of these from this single file.
services:
  # ------------------
  # The Flask API Server
  # ------------------
  - type: web
    name: flask-backend
    env: python
    # rootDir is removed because your files are in the main directory
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT server:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      # This will get the connection string from the database service below
      - key: DATABASE_URL
        fromDatabase:
          name: my-livekit-db # Must match the database 'name' below
          property: internalConnectionString
      # The rest of your secrets will be set in the Render dashboard
      - key: LIVEKIT_URL
        fromEnvironment: LIVEKIT_URL
      - key: LIVEKIT_API_KEY
        fromEnvironment: LIVEKIT_API_KEY
      - key: LIVEKIT_API_SECRET
        fromEnvironment: LIVEKIT_API_SECRET

  # ---------------------
  # The LiveKit Python Agent
  # ---------------------
  - type: worker
    name: livekit-agent
    env: python
    # rootDir is removed. The build command is fixed to download models.
    buildCommand: "pip install -r requirements.txt && python3 agent.py download-files"
    startCommand: "python agent.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: DATABASE_URL
        fromDatabase:
          name: my-livekit-db
          property: internalConnectionString
      - key: LIVEKIT_URL
        fromEnvironment: LIVEKIT_URL
      - key: LIVEKIT_API_KEY
        fromEnvironment: LIVEKIT_API_KEY
      - key: LIVEKIT_API_SECRET
        fromEnvironment: LIVEKIT_API_SECRET
# ---------------------------------------------
# A Persistent PostgreSQL Database
# This will replace your temporary auto_db.sqlite
# ---------------------------------------------
# databases:
#   - name: my-livekit-db
#     databaseName: my_livekit_db_data # You can name this whatever you want
#     user: livekit_user # You can name this whatever you want
#     plan: free # Use the free plan to start
