# render.yaml - v2 - CORRECTED and SIMPLIFIED

# This blueprint defines two services and a database.
# Secrets like API keys should be added manually in the Render dashboard.
services:
  # ------------------
  # The Flask API Server
  # ------------------
  - type: web
    name: flask-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT server:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      # This correctly links the database URL to this service.
      - key: DATABASE_URL
        fromDatabase:
          name: my-livekit-db
          property: connectionString # CORRECTED PROPERTY

  # ---------------------
  # The LiveKit Python Agent
  # ---------------------
  - type: worker
    name: livekit-agent
    env: python
    buildCommand: "pip install -r requirements.txt && python3 agent.py download-files"
    startCommand: "python agent.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      # This correctly links the database URL to this service as well.
      - key: DATABASE_URL
        fromDatabase:
          name: my-livekit-db
          property: connectionString # CORRECTED PROPERTY

# ---------------------------------------------
# A Persistent PostgreSQL Database
# (This section was already correct)
# ---------------------------------------------
databases:
  - name: my-livekit-db
    databaseName: my_livekit_db_data
    user: livekit_user
    plan: free